addons:
- attachPolicyARNs:
  - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  name: vpc-cni
  tags:
    team: mlops
    usage: kubeflow
  wellKnownPolicies:
    autoScaler: false
    awsLoadBalancerController: false
    certManager: false
    ebsCSIController: false
    efsCSIController: false
    externalDNS: false
    imageBuilder: false
- name: coredns
  tags:
    team: mlops
    usage: kubeflow
  version: latest
  wellKnownPolicies:
    autoScaler: false
    awsLoadBalancerController: false
    certManager: false
    ebsCSIController: false
    efsCSIController: false
    externalDNS: false
    imageBuilder: false
- name: kube-proxy
  tags:
    team: mlops
    usage: kubeflow
  version: latest
  wellKnownPolicies:
    autoScaler: false
    awsLoadBalancerController: false
    certManager: false
    ebsCSIController: false
    efsCSIController: false
    externalDNS: false
    imageBuilder: false
- name: aws-ebs-csi-driver
  tags:
    team: mlops
    usage: kubeflow
  wellKnownPolicies:
    autoScaler: false
    awsLoadBalancerController: false
    certManager: false
    ebsCSIController: true
    efsCSIController: false
    externalDNS: false
    imageBuilder: false
apiVersion: eksctl.io/v1alpha5
availabilityZones:
- us-east-1a
- us-east-1b
iam:
  vpcResourceControllerPolicy: true
  withOIDC: true
kind: ClusterConfig
managedNodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 2
  disableIMDSv1: false
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: false
      appMesh: null
      appMeshPreview: null
      autoScaler: false
      awsLoadBalancerController: false
      certManager: false
      cloudWatch: false
      ebs: false
      efs: false
      externalDNS: false
      fsx: false
      imageBuilder: false
      xRay: false
  instanceSelector: {}
  instanceType: t2.medium
  labels:
    alpha.eksctl.io/cluster-name: kubeflow
    alpha.eksctl.io/nodegroup-name: managed-ng-t2
    ng: managed-ng-t2
  maxSize: 3
  minSize: 2
  name: managed-ng-t2
  privateNetworking: false
  releaseVersion: ""
  securityGroups:
    withLocal: null
    withShared: null
  ssh:
    allow: false
  tags:
    alpha.eksctl.io/nodegroup-name: managed-ng-t2
    alpha.eksctl.io/nodegroup-type: managed
    nodegroup-role: managed-ng-t2
    team: mlops
    usage: kubeflow
  volumeIOPS: 3000
  volumeSize: 20
  volumeThroughput: 125
  volumeType: gp3
- amiFamily: AmazonLinux2
  desiredCapacity: 2
  disableIMDSv1: false
  disablePodIMDS: false
  iam:
    withAddonPolicies:
      albIngress: false
      appMesh: null
      appMeshPreview: null
      autoScaler: false
      awsLoadBalancerController: false
      certManager: false
      cloudWatch: false
      ebs: false
      efs: false
      externalDNS: false
      fsx: false
      imageBuilder: false
      xRay: false
  instanceSelector: {}
  instanceType: t3.medium
  labels:
    alpha.eksctl.io/cluster-name: kubeflow
    alpha.eksctl.io/nodegroup-name: managed-ng-t3
    ng: managed-ng-t3
  maxSize: 3
  minSize: 2
  name: managed-ng-t3
  privateNetworking: false
  releaseVersion: ""
  securityGroups:
    withLocal: null
    withShared: null
  ssh:
    allow: false
  tags:
    alpha.eksctl.io/nodegroup-name: managed-ng-t3
    alpha.eksctl.io/nodegroup-type: managed
    nodegroup-role: managed-ng-t3
    team: mlops
    usage: kubeflow
  volumeIOPS: 3000
  volumeSize: 20
  volumeThroughput: 125
  volumeType: gp3
metadata:
  name: kubeflow
  region: us-east-1
  tags:
    team: mlops
    usage: kubeflow
  version: "1.25"
privateCluster:
  enabled: false
  skipEndpointCreation: false
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single
