cluster:
  name: kubeflow
  region: us-east-1
kubeflow:
  alb:
    scheme: internet-facing
route53:
  rootDomain:
    hostedZoneId: Z04585768MD2C7VY6ET6
    name: cmcloudlab614.info
  subDomain:
    name: platform.cmcloudlab614.info
