cluster:
  name: kubeflow
  region: us-east-1
kubeflow:
  alb:
    scheme: internet-facing
route53:
  rootDomain:
    hostedZoneId: Z07716772EQW6Z6U1P43J
    name: cmcloudlab1681.info
  subDomain:
    name: platform.cmcloudlab1681.info
