cluster:
  name: kubeflow
  region: us-east-1
kubeflow:
  alb:
    scheme: internet-facing
route53:
  rootDomain:
    hostedZoneId: Z05207741CGXISAU5R2V9
    name: cmcloudlab1747.info
  subDomain:
    name: platform.cmcloudlab1747.info
